# -*- coding: utf-8 -*-
"""niswana_technocolob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8AR8Aj1Aft5608ThuBhVJg-8j8FiLf9
"""

# 1. Import libraries
import pandas as pd
import numpy as np

# 2. Load datasets
delivery_data = pd.read_csv('cleaned_delivery_data.csv')
pickup_data = pd.read_csv('cleaned_pickup_data.csv')

# 3. Merge datasets
merged_data = pd.merge(delivery_data, pickup_data, on='order_id', how='inner')

# 4. Check dataset
print(merged_data.shape)
print(merged_data.info())
print(merged_data.isnull().sum())

# 5. Drop fully null columns
all_null_columns = merged_data.columns[merged_data.isnull().all()]
merged_data.drop(columns=all_null_columns, inplace=True)

# 6. Handle missing values
numerical_cols = merged_data.select_dtypes(include=['number']).columns

for col in numerical_cols:
    merged_data[col] = merged_data[col].fillna(merged_data[col].mean())

# 7. Remove duplicates
merged_data.drop_duplicates(inplace=True)

# 8. Standardize column names
merged_data.columns = merged_data.columns.str.lower()
merged_data.columns = merged_data.columns.str.replace(' ', '_')

# Create a consolidated 'city' column from 'city_x' for consistency
# If 'city_y' is preferred, change 'city_x' to 'city_y'
merged_data['city'] = merged_data['city_x']

# 9. Convert data types
merged_data['city'] = merged_data['city'].astype(str)

# 10. Timestamp processing
merged_data['date'] = pd.to_datetime(
    merged_data['ds_x'],
    unit='D',
    origin='2000-01-01'
)

merged_data['day_of_week'] = merged_data['date'].dt.dayofweek
merged_data['day_of_month'] = merged_data['date'].dt.day
merged_data['is_weekend'] = merged_data['date'].dt.weekday >= 5

# 11. Feature engineering
merged_data['pickup_delivery_distance'] = np.sqrt(
    (merged_data['pickup_gps_lng'] - merged_data['delivery_gps_lng'])**2 +
    (merged_data['pickup_gps_lat'] - merged_data['delivery_gps_lat'])**2
)

# 12. Label encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
merged_data['city_encoded'] = le.fit_transform(merged_data['city'])

# 13. Outlier checking
def check_outliers(df, col, min_val, max_val):
    return df[(df[col] < min_val) | (df[col] > max_val)]

check_outliers(merged_data, 'lat_x', 20, 50)

# 14. Final check
print(merged_data.isnull().sum())
print(merged_data.head())

